import { Outfit } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import appAppleIcon from "./favicon-for-app/apple-icon.png";
import appIconPng from "./favicon-for-app/icon1.png";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Hritik.blogs",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      {
        url: "/favicon-for-public/web-app-manifest-192x192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        url: "/favicon-for-public/web-app-manifest-512x512.png",
        sizes: "512x512",
        type: "image/png",
      },
      {
        url: appIconPng.src,
        sizes: "512x512",
        type: "image/png",
      },
    ],
    apple: [
      {
        url: appAppleIcon.src,
        sizes: "180x180",
        type: "image/png",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${outfit.variable} h-full antialiased`}>
      <meta name="apple-mobile-web-app-title" content="Hritik.blogs" />
      <body className="min-h-screen">
        <ToastContainer theme="dark" />
        <div>
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
